services:
  app:
    build: .
    environment:
      CONFIG_ENV: ${CONFIG_ENV}
      SESSION_SECRET_KEY: ${SESSION_SECRET_KEY}
      ACCESS_TOKEN_SECRET_KEY: ${ACCESS_TOKEN_SECRET_KEY}
      REFRESH_TOKEN_SECRET_KEY: ${REFRESH_TOKEN_SECRET_KEY}
      HTTP_HOST: ${HTTP_HOST}
      HTTP_PORT: ${HTTP_PORT}
      PG_WRITE_CONNECTION_STRING: ${PG_WRITE_CONNECTION_STRING}
      PG_READ_CONNECTION_STRING: ${PG_READ_CONNECTION_STRING}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      DEACTIVATED_JOBS: ${DEACTIVATED_JOBS}
      LDAP_URL: ${LDAP_URL}
      LDAP_LOGIN: ${LDAP_LOGIN}
      LDAP_PASSWORD: ${LDAP_PASSWORD}
      LDAP_DC: ${LDAP_DC}
    depends_on:
      - db
      - redis
    container_name: app
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: db
    ports:
      - "5432:5432"

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
