version: '3'

services:
  app:
    build: .
    environment:
      CONFIG_ENV: ${CONFIG_ENV}
      HTTP_HOST: ${HTTP_HOST}
      HTTP_PORT: ${HTTP_PORT}
      PG_WRITE_CONNECTION_STRING: ${PG_WRITE_CONNECTION_STRING}
      PG_READ_CONNECTION_STRING: ${PG_READ_CONNECTION_STRING}
    depends_on:
      - db
    container_name: app
    ports:
      - '8080:8080'

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: db
    ports:
      - '5432:5432'
